# Generated by Django 5.0 on 2026-01-21 19:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Catégorie d'équipement",
                'verbose_name_plural': "Catégories d'équipements",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('TECHNICIEN', 'Technicien'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='maintenance.direction')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['direction', 'nom'],
                'unique_together': {('nom', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('code_equipement', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=100)),
                ('date_acquisition', models.DateField()),
                ('description_technique', models.TextField(blank=True, null=True)),
                ('bureau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='maintenance.bureau')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='maintenance.categorieequipement')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['code_equipement'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgence', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute')], default='MOYENNE', max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ASSIGNEE', 'Assignée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('email_envoye', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(limit_choices_to={'role': 'EMPLOYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_assignees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='maintenance.equipement')),
            ],
            options={
                'verbose_name': 'Demande de maintenance',
                'verbose_name_plural': 'Demandes de maintenance',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('type_reparation', models.CharField(choices=[('INTERNE', 'Réparation Interne'), ('EXTERNE', 'Réparation Externe')], default='INTERNE', max_length=20)),
                ('date_intervention', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='maintenance.demandemaintenance')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='maintenance.intervention')),
            ],
            options={
                'verbose_name': 'Pièce de rechange',
                'verbose_name_plural': 'Pièces de rechange',
            },
        ),
    ]
