# Generated by Django 5.0 on 2026-01-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_user_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichierIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='interventions/%Y/%m/', verbose_name='Fichier')),
                ('type_fichier', models.CharField(choices=[('FACTURE', 'Facture'), ('PHOTO_AVANT', 'Photo Avant Réparation'), ('PHOTO_APRES', 'Photo Après Réparation'), ('DEVIS', 'Devis'), ('DIAGNOSTIC', 'Rapport de Diagnostic'), ('GARANTIE', 'Certificat de Garantie'), ('AUTRE', 'Autre Document')], default='AUTRE', max_length=20, verbose_name='Type de fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (bytes)')),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='maintenance.intervention')),
            ],
            options={
                'verbose_name': "Fichier d'intervention",
                'verbose_name_plural': "Fichiers d'intervention",
                'ordering': ['type_fichier', '-date_ajout'],
            },
        ),
    ]
