# Generated by Django 5.0 on 2026-02-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_fichierintervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEMANDE_CREATION', 'Création de demande'), ('DEMANDE_MODIFICATION', 'Modification de demande'), ('DEMANDE_SUPPRESSION', 'Suppression de demande'), ('DEMANDE_VALIDATION', 'Validation de réparation'), ('DEMANDE_REFUS', 'Refus de réparation'), ('INTERVENTION_CREATION', "Création de rapport d'intervention"), ('INTERVENTION_MODIFICATION', 'Modification de rapport'), ('STATUT_CHANGE', 'Changement de statut'), ('FICHIER_UPLOAD', 'Upload de fichier'), ('ASSIGNATION', 'Assignation de technicien'), ('EQUIPEMENT_CREATION', "Création d'équipement"), ('EQUIPEMENT_MODIFICATION', "Modification d'équipement"), ('EQUIPEMENT_SUPPRESSION', "Suppression d'équipement"), ('IMPORT_CSV', 'Import CSV'), ('EXPORT_CSV', 'Export CSV'), ('EXPORT_PDF', 'Export PDF'), ('EXPORT_WORD', 'Export Word'), ('FICHIER_SUPPRESSION', 'Suppression de fichier'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion')], max_length=50)),
                ('type_objet', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'action",
                'verbose_name_plural': "Logs d'actions",
                'ordering': ['-date_action'],
            },
        ),
    ]
