# Generated by Django 5.0 on 2026-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_logaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaction',
            name='action',
            field=models.CharField(choices=[('DEMANDE_CREATION', 'Création de demande'), ('DEMANDE_MODIFICATION', 'Modification de demande'), ('DEMANDE_SUPPRESSION', 'Suppression de demande'), ('DEMANDE_VALIDATION', 'Validation de réparation'), ('DEMANDE_REFUS', 'Refus de réparation'), ('INTERVENTION_CREATION', "Création de rapport d'intervention"), ('INTERVENTION_MODIFICATION', 'Modification de rapport'), ('STATUT_CHANGE', 'Changement de statut'), ('FICHIER_UPLOAD', 'Upload de fichier'), ('ASSIGNATION', 'Assignation de technicien'), ('EQUIPEMENT_CREATION', "Création d'équipement"), ('EQUIPEMENT_MODIFICATION', "Modification d'équipement"), ('EQUIPEMENT_SUPPRESSION', "Suppression d'équipement"), ('FICHIER_SUPPRESSION', 'Suppression de fichier'), ('IMPORT_CSV', 'Import CSV'), ('EXPORT_CSV', 'Export CSV'), ('EXPORT_PDF', 'Export PDF'), ('EXPORT_WORD', 'Export Word')], max_length=50),
        ),
    ]
